include scripts/utilities.mak
include scripts/feature-tests.mak

CONFIG := src/include/config.h

$(CONFIG): scripts/utilities.mak scripts/feature-tests.mak
	$(E) "  GEN     " $@
	$(Q) @echo '#ifndef __COMPEL_CONFIG_H__' > $@
	$(Q) @echo '#define __COMPEL_CONFIG_H__' >> $@
ifeq ($(call try-cc,$(STRLCPY_TEST),,),y)
	$(Q) @echo '#define CONFIG_HAS_STRLCPY' >> $@
endif
ifeq ($(call try-cc,$(STRLCAT_TEST),,),y)
	$(Q) @echo '#define CONFIG_HAS_STRLCAT' >> $@
endif
	$(Q) @echo '#endif /* __COMPEL_CONFIG_H__ */' >> $@

config: $(CONFIG)

.PHONY: config
